apiVersion: apps/v1
kind: Deployment
metadata:
  name: bicycles-deployment
  namespace: backend
  labels:
    app: bicycles-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bicycles-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bicycles-app
    spec:
      containers:
      - name: bicycles-app
        image: ariosg55/bicycles-fastapi
        imagePullPolicy: "Always"
        ports:
          - name: http2
            containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: bicycles-service
  namespace: backend
spec:
  selector:
    app: bicycles-app
  ports:
    - name: http2
      port: 8000
      targetPort: 8000
  type: NodePort
  
