apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
  namespace: tiwala-backend
  labels:
    app: authenticationapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authenticationapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: authenticationapp
    spec:
      containers:
      - name: authenticationapp
        image: devteamtwelve/repo.pkg.authentication.backbone.tiwala.com.co:auth-kube
        imagePullPolicy: "Always"
        env:
        - name: REDIS_HOST
          value: "redis-service.tiwala-backend.svc.cluster.local"
        - name: MYSQL_DATABASE
          value: "auth_service"
        - name: MYSQL_USER
          value: "tiwala_user"
        - name: MYSQL_PASSWORD
          value: "Es9Kvyq2JMGDKmAH"
        - name: MYSQL_HOST
          value: "104.248.230.68"
        ports:
          - name: http2
            containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
      imagePullSecrets:
      - name: dockerhub2
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: tiwala-backend
spec:
  selector:
    app: authenticationapp
  ports:
    - name: http2
      port: 8000
      targetPort: 8000

  
